#!/usr/bin/env bash

set -euo pipefail

apache_pid=""
app_entrypoint_pid=""
tail_pid=""

_term() {
  if [[ -n "${apache_pid}" ]]; then
    _out "Shutdown Apache"
    kill -WINCH "${apache_pid}" || true
    wait "${apache_pid}"
    _out "Apache exited"
  fi

  if [[ -n "${app_entrypoint_pid}" ]]; then
    _out "Shutdown App"
    kill "${app_entrypoint_pid}" || true
    wait "${app_entrypoint_pid}"
    _out "App exited"
  fi

  if [[ -n "${tail_pid}" ]]; then
    _out "Shutdown tail"
    kill "${tail_pid}" || true
    wait "${tail_pid}"
    _out "tail exited"
  fi

  _out "Bye"
  exit 0
}

_out() {
  echo "⚡️ $*"
}

trap "_term" TERM INT

_exec_dev_app() {
  local reflex_conf="${APP_ROOT}/_reflex.conf"
  local default_reflex_conf="/etc/default/reflex.conf"

  while true; do
    if [[ -f "${reflex_conf}" ]]; then
      _out "Found '${reflex_conf}'"
      break
    else
      _out "Initialize default reflex.conf .."
      cp -v "${default_reflex_conf}" "${reflex_conf}"

      sleep 0.5
    fi
  done

  exec reflex --verbose=true -c "${reflex_conf}"
}

_init_entrypoint() {
  local default_app_entrypoint="/etc/default/entrypoint"

  while true; do
    if [[ -f "${APP_ENTRYPOINT}" ]]; then
      _out "Found '${APP_ENTRYPOINT}'"
      chmod +x "${APP_ENTRYPOINT}"

      break
    else
      _out "Initialize default entrypoint .."
      cp -v "${default_app_entrypoint}" "${APP_ENTRYPOINT}"

      sleep 0.5
    fi
  done
}

_out "Start Apache"
apachectl -DFOREGROUND &
apache_pid=$!

_out "Init app"
APP_ROOT="${APP_ROOT:-"/a/shared/app"}"
APP_ENTRYPOINT="${APP_ROOT}/_entrypoint"
_out "APP_ROOT: ${APP_ROOT}"
_out "APP_ENTRYPOINT: ${APP_ENTRYPOINT}"
_init_entrypoint

_out "Start app"
>/dev/null pushd "${APP_ROOT}"

(
  if [[ "${DEV_MODE:-}" = "yes" ]]; then
    _exec_dev_app
  else
    # shellcheck disable=SC2086
    exec ${APP_ENTRYPOINT}
  fi
) >/dev/stdout 2>&1 &
app_entrypoint_pid=$!

_out "Waiting for signals .."
tail -f /dev/null &
tail_pid=$!
wait ${tail_pid}
