#!/usr/bin/env bash

set -euo pipefail

nodejs_pid=""

_out() {
  echo "Entrypoint: $*"
}

_term() {
  >&2 echo "TERM"

  echo "Shutdown Node.js"
  kill "${nodejs_pid}" || true
  wait "${nodejs_pid}"
  echo "Node.js exited"

  exit 0
}

trap "_term" TERM INT

pushd /a/shared/app

node index.js &
nodejs_pid=$!

_out "Waiting for signals .."
tail -f /dev/null &
tail_pid=$!
wait ${tail_pid}
